global:
    scrape_interval: 10s

scrape_configs:
  - job_name: Prometheus Server
    static_configs:
       - targets: ['localhost:9090']
         
  - job_name: Prometheus Server nodex
    static_configs:
       - targets: ['localhost:9100']

  - job_name: Prometheus Server blackex
    static_configs:
       - targets: ['localhost:9115']

  - job_name: Prometheus Target nodex
    static_configs:
       - targets: ['192.168.56.111:9100']

  - job_name: Prometheus Server blackex - ICMP_check
    metrics_path: /probe
    params:
       module: [icmp_v4]
    static_configs:
       - targets:
           - 4.2.2.4
           - www.anisa.co.ir
    relabel_configs:
       - source_labels: [__address__]
         target_label: __param_target
       - source_labels: [__address__]
         target_label: instance
       - target_label: __address__
         replacement: 127.0.0.1:9115
    
  - job_name: CAdvisor 
    static_configs:
       - targets: [172.16.52.40:8080]
