tls_server_config:
  cert_file: /etc/prometheus/tls/prometheus.crt
  key_file: /etc/prometheus/tls/prometheus.key

basic_auth_users:
  admin: $2y$05$mZQct/oF9piMwC302rt7YeWik5INASb6SpfWP4Ycei8Sr6oTlEyCG
